# Generated by Django 3.2 on 2021-05-01 01:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20210430_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
