# Generated by Django 3.2 on 2021-05-01 01:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_alter_course_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
